# -*- coding: utf-8 -*-
"""
OpenAI 兼容模型列表数据
"""

MODELS = [
    "gpt-5.5", "gpt-5.4", "gpt-5.3", "gpt-5.2", "gpt-5.1", "gpt-5", "gpt-5-pro",
    "gpt-4o", "gpt-4-turbo", "gpt-4", "gpt-3.5-turbo",
    "o3", "o3-mini", "o4-mini", "o1", "o1-mini", "deep-research",
    "claude-opus-4.6", "claude-sonnet-4.6", "claude-haiku-4.5",
    "claude-3-opus", "claude-3-sonnet", "claude-3-haiku",
    "claude-3.5-sonnet", "claude-3.7-sonnet",
    "gemini-3.1-pro", "gemini-3.1-flash-lite", "gemini-3-pro", "gemini-3-flash",
    "gemini-2.0-pro", "gemini-2.0-flash", "gemini-1.5-pro", "gemini-1.5-flash",
    "gemini-ultra", "gemini-pro", "gemini-flash", "gemini-nano",
    "gemma-2-27b", "gemma-2-9b", "gemma-2-2b",
    "llama-4", "llama-3.3-70b", "llama-3.2", "llama-3.1-405b", "llama-3.1-70b",
    "llama-3.1-8b", "llama-3-70b", "llama-3-8b", "llama-guard-3", "mobile-llama",
    "deepseek-v4", "deepseek-v3.2", "deepseek-v3", "deepseek-r1", "deepseek-r1-0528",
    "deepseek-chat", "deepseek-coder",
    "qwen-3.5", "qwen-3.5-max", "qwen-3.5-plus", "qwen-3.5-turbo", "qwen-3.5-397b",
    "qwen-3-max", "qwen-3-plus", "qwen-3-turbo", "qwen-3-embedding",
    "qwen-2.5-72b", "qwen-2.5-32b", "qwen-2.5-14b", "qwen-2.5-7b", "qwen-2.5-3b",
    "qwen-2.5-1.5b", "qwen-2.5-0.5b", "qwen-2.5-coder",
    "qwen-3-coder-next", "qwen-3-coder", "qwen-max", "qwen-plus", "qwen-turbo", "qwen-omni",
    "doubao-2.0", "doubao-pro-256k", "doubao-pro-32k", "doubao-lite-32k",
    "seedance-2.0", "bitdance", "concept-moe", "doubao-vision", "doubao-embedding",
    "doubao-realtime", "doubao-voice", "x-agents", "seed-music", "seed-video", "seed-tts", "seed-ocr",
    "glm-5.1", "glm-5", "glm-4.7", "glm-4-plus", "glm-4-long", "glm-4-flash", "glm-4-air",
    "glm-4v-plus", "glm-z1-air", "glm-3-turbo", "glm-ocr", "z-code",
    "wenxin-5.0", "wenxin-4.0-turbo", "wenxin-4.0", "wenxin-3.5", "wenxin-lite",
    "wenxin-embeddings", "wenxin-ocr", "wenxin-speech",
    "kimi-k2.5", "kimi-v2", "moonshot-v1-128k", "moonshot-v1-32k", "moonshot-v1-8k",
    "simple-seg", "kimi-vision", "kimi-voice",
    "minimax-m2.7", "minimax-m2.5", "abab-7-chat", "abab-6.5-chat", "abab-5.5-chat",
    "minimax-speech", "minimax-voice-clone", "minimax-video", "minimax-embedding",
    "yi-large-2", "yi-large", "yi-medium", "yi-spark", "yi-vision", "yi-34b", "yi-6b",
    "hunyuan-hy3-preview", "hunyuan-3.0", "hunyuan-pro", "hunyuan-standard", "hunyuan-lite",
    "hunyuan-1.8b-2bit", "hpc-ops",
    "spark-x2-flash", "spark-x2", "spark-v4.0", "spark-v3.5", "spark-lite",
    "spark-tts", "spark-ocr", "spark-review",
    "360gpt-pro", "360gpt-turbo", "360gpt",
    "sensetime-nova", "sensetime-pro", "sensetime-lite", "sensetime-vision", "sensetime-vega",
    "skywork-13b", "skywork-7b", "skywork-3b", "skywork-code", "skywork-voice",
    "mimo-v2-flash-0204", "mimo-v2", "mimo-embed", "mimo-vision", "mimo-voice",
    "mimo-agent", "mimo-code", "mimo-translate", "mimo-summary", "mimo-recommend", "mimo-search",
    "step-3.5-flash", "step-3.5", "step-3", "step-2", "step-vision", "step-audio",
    "ling-2.5-1t", "ring-2.5-1t", "llada-2.1", "ming-flash-omni-2.0", "ming-omni-tts",
    "ant-llm", "ant-vision", "ant-embedding", "ant-rag",
    "joyai-llm-flash", "joyai-pro", "joyai-lite", "joyai-code", "joyai-chat",
    "joyai-vision", "joyai-voice", "joyai-embedding", "joyai-agent",
    "joyai-recommend", "joyai-search", "joyai-summary", "joyai-translate", "joyai-summary-agent",
    "longcat-flash-lite", "longcat-pro", "longcat-lite", "longcat-chat", "longcat-agent",
    "rednote-fireasr-2s", "rednote-image-edit", "rednote-nlp", "rednote-cv", "rednote-voice",
    "rednote-translate", "rednote-summary", "rednote-rag", "rednote-agent", "rednote-rec",
    "rednote-chat", "rednote-search", "rednote-recommend", "rednote-embedding",
    "rednote-vision", "rednote-metric", "rednote-training",
    "firefly-llm", "firefly-embedding", "firefly-search", "firefly-recommend",
    "firefly-nlp-base", "firefly-cv-base", "firefly-agent", "firefly-chat",
    "kling-3.0", "kling-2.5", "kling-pro", "kling-standard", "kling-vision", "kling-audio",
    "kling-embedding", "kling-agent", "kling-code", "kling-translate", "kling-summary",
    "kling-recommend", "kling-search", "kwai-llm", "kwai-chat",
    "honor-ai", "honor-vision", "honor-voice", "honor-embedding", "honor-agent",
    "honor-chat", "honor-summary", "honor-translate", "honor-recommend", "honor-search",
    "honor-magic", "honor-magic-pro", "honor-magic-lite",
    "zte-ai", "zte-ai-pro", "zte-ai-lite",
    "oppo-ai", "oppo-ai-pro", "oppo-ai-lite", "oppo-ai-agent", "oppo-ai-chat", "oppo-ai-vision",
    "vivo-ai", "vivo-ai-pro", "vivo-ai-lite", "vivo-ai-chat", "vivo-ai-agent",
    "vivo-ai-vision", "vivo-ai-voice", "vivo-ai-embedding", "vivo-ai-summary",
    "vivo-ai-recommend", "vivo-ai-search", "vivo-ai-translate", "vivo-ai-code",
    "vivo-ai-agent-pro", "vivo-ai-chat-pro", "vivo-ai-vision-pro", "vivo-ai-voice-pro",
    "vivo-ai-embedding-pro", "vivo-ai-summary-pro", "vivo-ai-recommend-pro",
    "vivo-ai-search-pro", "vivo-ai-translate-pro", "vivo-ai-code-pro",
    "grok-4.2", "grok-4.1", "grok-4", "grok-3", "grok-2.5", "grok-2",
    "grok-imagine-1.0", "grok-vision", "grok-audio", "grok-embedding", "grok-agent",
    "grok-summary", "grok-recommend", "grok-search", "grok-translate", "grok-chat",
    "grok-code", "grok-reasoning", "grok-multiagent", "grok-pro", "grok-lite",
    "grok-realtime", "grok-voice", "grok-ocr", "grok-rag", "grok-funcall", "grok-web",
    "mistral-large-3", "mistral-large-2", "mistral-medium", "mistral-small-3",
    "mistral-small", "mixtral-8x22b", "mixtral-8x7b",
    "codestral", "codestral-mamba", "voxtral-mini-4b", "voxtral", "mathstral", "pixtral",
    "mistral-embed", "mistral-vision", "mistral-funcall",
    "qoder-3.5", "qoder-3", "qoder-2", "qoder-vision", "qoder-embed", "qoder-summary",
    "qoder-recommend", "qoder-search", "qoder-translate", "qoder-agent", "qoder-web",
    "qoder-operation", "qoder-management", "qoder-leadership", "qoder-team",
    "qoder-project", "qoder-product", "qoder-design", "qoder-ux", "qoder-ui",
]

MODELS_CACHE = [{"id": m, "object": "model"} for m in MODELS]
